/*
Copyright Neaj Morshad.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1beta1 "github.com/Neaj-Morshad-101/crd-controller/pkg/apis/neajmorshad.dev/v1beta1"
	neajmorshaddevv1beta1 "github.com/Neaj-Morshad-101/crd-controller/pkg/client/applyconfiguration/neajmorshad.dev/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKlusters implements KlusterInterface
type FakeKlusters struct {
	Fake *FakeNeajmorshadV1beta1
	ns   string
}

var klustersResource = v1beta1.SchemeGroupVersion.WithResource("klusters")

var klustersKind = v1beta1.SchemeGroupVersion.WithKind("Kluster")

// Get takes name of the kluster, and returns the corresponding kluster object, and an error if there is any.
func (c *FakeKlusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.Kluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(klustersResource, c.ns, name), &v1beta1.Kluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Kluster), err
}

// List takes label and field selectors, and returns the list of Klusters that match those selectors.
func (c *FakeKlusters) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.KlusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(klustersResource, klustersKind, c.ns, opts), &v1beta1.KlusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.KlusterList{ListMeta: obj.(*v1beta1.KlusterList).ListMeta}
	for _, item := range obj.(*v1beta1.KlusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested klusters.
func (c *FakeKlusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(klustersResource, c.ns, opts))

}

// Create takes the representation of a kluster and creates it.  Returns the server's representation of the kluster, and an error, if there is any.
func (c *FakeKlusters) Create(ctx context.Context, kluster *v1beta1.Kluster, opts v1.CreateOptions) (result *v1beta1.Kluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(klustersResource, c.ns, kluster), &v1beta1.Kluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Kluster), err
}

// Update takes the representation of a kluster and updates it. Returns the server's representation of the kluster, and an error, if there is any.
func (c *FakeKlusters) Update(ctx context.Context, kluster *v1beta1.Kluster, opts v1.UpdateOptions) (result *v1beta1.Kluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(klustersResource, c.ns, kluster), &v1beta1.Kluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Kluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKlusters) UpdateStatus(ctx context.Context, kluster *v1beta1.Kluster, opts v1.UpdateOptions) (*v1beta1.Kluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(klustersResource, "status", c.ns, kluster), &v1beta1.Kluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Kluster), err
}

// Delete takes name of the kluster and deletes it. Returns an error if one occurs.
func (c *FakeKlusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(klustersResource, c.ns, name, opts), &v1beta1.Kluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKlusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(klustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.KlusterList{})
	return err
}

// Patch applies the patch and returns the patched kluster.
func (c *FakeKlusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Kluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(klustersResource, c.ns, name, pt, data, subresources...), &v1beta1.Kluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Kluster), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied kluster.
func (c *FakeKlusters) Apply(ctx context.Context, kluster *neajmorshaddevv1beta1.KlusterApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.Kluster, err error) {
	if kluster == nil {
		return nil, fmt.Errorf("kluster provided to Apply must not be nil")
	}
	data, err := json.Marshal(kluster)
	if err != nil {
		return nil, err
	}
	name := kluster.Name
	if name == nil {
		return nil, fmt.Errorf("kluster.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(klustersResource, c.ns, *name, types.ApplyPatchType, data), &v1beta1.Kluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Kluster), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeKlusters) ApplyStatus(ctx context.Context, kluster *neajmorshaddevv1beta1.KlusterApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.Kluster, err error) {
	if kluster == nil {
		return nil, fmt.Errorf("kluster provided to Apply must not be nil")
	}
	data, err := json.Marshal(kluster)
	if err != nil {
		return nil, err
	}
	name := kluster.Name
	if name == nil {
		return nil, fmt.Errorf("kluster.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(klustersResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1beta1.Kluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Kluster), err
}
